using ThreeXPlusOne.App.Enums;

namespace ThreeXPlusOne.App.Interfaces.DirectedGraph;

public interface IDirectedGraph
{
    /// <summary>
    /// The type of the graph that will be rendered.
    /// </summary>
    GraphType GraphType { get; }

    /// <summary>
    /// Add multiple series of numbers generated by the algorithm to the directed graph.
    /// </summary>
    /// <param name="seriesLists"></param>
    void AddSeries(List<List<int>> seriesLists);

    /// <summary>
    /// Position the nodes on the directed graph bassed on the provided app settings.
    /// </summary>
    void PositionNodes();

    /// <summary>
    /// Set the shape of each node to either circle or polygon, depending on app settings.
    /// </summary>
    void SetNodeAesthetics();

    /// <summary>
    /// Assign sizes to the canvas width and height after having positioned the nodes.
    /// </summary>
    void SetCanvasDimensions();

    /// <summary>
    /// Generate a visual representation of the directed graph based on the app settings.
    /// </summary>
    Task Draw();
}