namespace ThreeXPlusOne.Code.Interfaces;

public interface IDirectedGraph
{
    /// <summary>
    /// The number of dimensions the graph will render in
    /// </summary>
    int Dimensions { get; }

    /// <summary>
    /// Add multiple series of numbers generated by the algorithm to the graph
    /// </summary>
    /// <param name="seriesLists"></param>
    void AddSeries(List<List<int>> seriesLists);

    /// <summary>
    /// Position the nodes on the graph bassed on the provided settings
    /// </summary>
    void PositionNodes();

    /// <summary>
    /// Generate a visual representation of the graph based on the settings
    /// </summary>
    void Draw();
}