namespace ThreeXPlusOne.App.Interfaces.Services;

public interface IFileService
{
    /// <summary>
    /// Save the app settings object values back to the app settings file
    /// </summary>
    /// <param name="userConfirmedSave"></param>
    void WriteSettingsToFile(bool userConfirmedSave);

    /// <summary>
    /// Check to see if a given file path already exists on the drive
    /// </summary>
    /// <param name="filePath"></param>
    /// <returns></returns>
    bool FileExists(string filePath);

    /// <summary>
    /// Save the metadata generated by the execution of the process to a file
    /// </summary>
    /// <param name="content"></param>
    /// <param name="filePath"></param>
    void WriteMetadataToFile(string content, string filePath);

    /// <summary>
    /// Create a directory and return the full path to the graph file
    /// </summary>
    /// <returns></returns>
    string GenerateDirectedGraphFilePath();

    /// <summary>
    /// Create a directory (if required) and return the full path to the histogram file
    /// </summary>
    /// <returns></returns>
    string GenerateHistogramFilePath();

    /// <summary>
    /// Create a directory (if required) and return the full path to the metadata file
    /// </summary>
    /// <returns></returns>
    string GenerateMetadataFilePath();
}