namespace ThreeXPlusOne.App.Models;

/// <summary>
/// A record capturing the generated values from the algorithm along with related metadata.
/// </summary>
public record CollatzResult
{
    /// <summary>
    /// The integer values generated by running the algorithm, including the original number.
    /// </summary>
    public List<int> Values { get; set; } = [];

    /// <summary>
    /// The number of steps it takes to get a number smaller than the original number for the first time.
    /// </summary>
    public int? StoppingTime { get; set; }

    /// <summary>
    /// The total number of steps it takes to get to 1.
    /// </summary>
    public int TotalStoppingTime { get; set; }
}