name: Branch Name Check - Creation

on:
  create:

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
    - name: Check Branch Name Format
      run: |
        if [[ ! "${{ github.ref }}" =~ ^refs/heads/(feature|bugfix)/[0-9]+-.* ]]; then
          echo "Error: Branch name does not follow the 'feature/0000-feature-name' or 'bugfix/0000-bugfix-name' format (where 0000 is the Issue Id). Pull requests will be prevented."
          exit 1
        fi
