# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "feature/*", "bugfix/*", "refactor/*" ]
  pull_request:
    branches: [ "main", "feature/*", "bugfix/*", "refactor/*" ]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    outputs:
      has_open_pr: ${{ steps.pr_check.outputs.has_open_pr }}
    steps:
      - id: pr_check
        uses: actions/github-script@v5
        with:
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${{ github.ref_name }}`,
              state: 'open'
            });
            const hasOpenPr = pullRequests.length > 0 ? 'true' : 'false';
            core.setOutput('has_open_pr', hasOpenPr);

  build:
    runs-on: ubuntu-latest
    needs: check-pr
    if: needs.check-pr.outputs.has_open_pr == 'false'
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal