name: Version Increment Check

on: pull_request

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout base branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
        path: base

    - name: Checkout head branch
      uses: actions/checkout@v2
      with:
        path: head

    - name: Compare versions
      run: |
        VERSION_BASE=$(grep -oP '<Version>\K[^<]+' base/ThreeXPlusOne/ThreeXPlusOne.csproj)
        VERSION_HEAD=$(grep -oP '<Version>\K[^<]+' head/ThreeXPlusOne/ThreeXPlusOne.csproj)
        echo "Base version: $VERSION_BASE"
        echo "Head version: $VERSION_HEAD"
        if [ "$VERSION_HEAD" = "$VERSION_BASE" ]; then
          echo "Version has not been incremented."
          exit 1
        fi
      shell: bash
