name: Version Increment Check

on: pull_request

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout base branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.base_ref }}
        path: base

    - name: Checkout head branch
      uses: actions/checkout@v3
      with:
        path: head

    - name: Compare versions
      run: |
          VERSION_BASE=$(grep -oP '<Version>\K[^<]+' base/ThreeXPlusOne/ThreeXPlusOne.csproj)
          VERSION_HEAD=$(grep -oP '<Version>\K[^<]+' head/ThreeXPlusOne/ThreeXPlusOne.csproj)

          TAG_MESSAGE_BASE=$(grep -oP '<TagMessage>\K[^<]+' base/ThreeXPlusOne/ThreeXPlusOne.csproj)
          TAG_MESSAGE_HEAD=$(grep -oP '<TagMessage>\K[^<]+' head/ThreeXPlusOne/ThreeXPlusOne.csproj)
          
          echo "Base Version: $VERSION_BASE"
          echo "Head Version: $VERSION_HEAD"

          echo "Base Tag Message: $TAG_MESSAGE_BASE"
          echo "Head Tag Message: $TAG_MESSAGE_HEAD"

          # Convert version numbers to an array (split by '.')
          IFS='.' read -r -a VERSION_BASE_ARRAY <<< "$VERSION_BASE"
          IFS='.' read -r -a VERSION_HEAD_ARRAY <<< "$VERSION_HEAD"
          
          # Initial comparison flag
          version_is_higher=false
          
          # Compare each segment of the version number
          for i in "${!VERSION_BASE_ARRAY[@]}"; do
            if [[ "${VERSION_HEAD_ARRAY[i]}" -gt "${VERSION_BASE_ARRAY[i]}" ]]; then
              version_is_higher=true
              break
            elif [[ "${VERSION_HEAD_ARRAY[i]}" -lt "${VERSION_BASE_ARRAY[i]}" ]]; then
              version_is_higher=false
              break
            fi
          done
          
          # Check if version is higher or tag message is different
          if [ "$version_is_higher" = false ] || [ "$TAG_MESSAGE_HEAD" = "$TAG_MESSAGE_BASE" ]; then
            echo "Version must be incremented and tag message must be changed."
            exit 1
          else
            echo "Version check passed."
          fi
      shell: bash
